### ISSUE TITLE
"Build Project" build step throws an error

### ISSUE THREAD

**Issue by Rockerby** [umbraco/Package.Templates#14]
When running the GitHub actions, on the "Build Project" I get the following error:

`Error: C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'D:\a\DuugTest_Richard\DuugTest_Richard\src\DuugTest_Richard\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [D:\a\DuugTest_Richard\DuugTest_Richard\src\DuugTest_Richard\DuugTest_Richard.csproj]`

I found by adding a `/t:Restore` to the build line it solved the issue:

`run: msbuild ./src -p:Configuration=${{ env.CONFIG }} /t:Restore`

**Comment by Rockerby** [comment]
https://github.com/umbraco/Package.Templates/pull/15

**Comment by KevinJump** [comment]
PR #17 - we've updates some paths and put the restore command in and updated the project file so paths are right.

**Comment by jmayntzhusen** [comment]
Yep @Rockerby to fully fix this a few extra steps were required. Will close this and #15 in favor of #17 🙂
