### ISSUE TITLE
Wrong path in package.xml

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Package.Templates#16]
If you install the Package project you get a package.xml file in the root of the solution that includes a file and folder that points to the dll and the app plugins folder of the package. Automatically replaces the name, and is a very nice touch!

https://github.com/umbraco/Package.Templates/blob/master/ProjectTemplates/UmbracoPackage.1/package.xml

Problem I've found though is that the dll is not exisiting when I build, it is found in the .website folder instead, so fx last time I had to edit from:

```xml
  <files>
    <folder path="src/Package.Workshop/App_Plugins/Package.Workshop" orgPath="App_Plugins/Package.Workshop" />
    <file path=".src/Package.Workshop/bin/release/Package.Workshop.dll" orgPath="bin/Package.Workshop.dll" />
  </files>
```

To:
```xml
  <files>
    <folder path=".website/App_Plugins/Package.Workshop" orgPath="App_Plugins/Package.Workshop" />
    <file path=".website/bin/Package.Workshop.dll" orgPath="bin/Package.Workshop.dll" />
  </files>
```

Are we expecting the dll to exist in the core project? Guess I may have needed to build as release instead of debug for that?

Maybe it's easier to change it to the website folder instead as we'd expect the testsite to have the correct files and be tested before packing it up, right?

**Comment by KevinJump** [comment]
ideally we want it to still reference the package not the site, because the .website folder isn't source controlled, and you have the option not to create a .website when you create your template.

I think there is a %configuraton% style variable (i will have to look it up) that you can replace the %release% with.

**Comment by KevinJump** [comment]
PR #17 Fixes this ?

**Comment by jmayntzhusen** [comment]
Yep, will close this 🙂
