### ISSUE TITLE
Keep Item and Project template in sync.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Package.Templates#6]
We need a mechanism in the repo to keep the code in the item template folders in sync with that in the project template ones (e.g dashboards). 

Something like a build event, or gulp script to copy the files between the two areas should be enough.

**Comment by KevinJump** [comment]
for an item template the template.json requires you to list the files you want to add to the solution - so at the moment the script copies the files to the folder, but it doesn't do this bit (loading the config as json adding to the array) - I am not sure automatic makes sense for that. 

So we will need to update the 'working with this repo' docs to say something like: 

When you update files that are used for an ItemTemplate
- run the gulp script to copy from `packagetemplates` to `itemtemplates`, 
- check the outputs of the template are what you expect them to be.

**Comment by LottePitcher** [comment]
I'll try and create a 'Content App' template to see if I can get this working / documented

**Comment by KevinJump** [comment]
Cool, I am around if you need help understanding my random ramblings.

**Comment by LottePitcher** [comment]
@KevinJump can we close this now? What's there works well enough I think?

**Comment by KevinJump** [comment]
yep
